### ISSUE TITLE
DIR_OUT/ DIR_IN/ DIR_OUT_LOW/ DIR_OUT_HIGH from mraa.Gpio() not recognized as a predefined values 

### ISSUE THREAD

**Issue by cosscat** [intel-iot-devkit/mraa#181]
Hello,

Came accross this issue wen trying to set the direction of a pin to output. I  can use the substitute value for the DIR_OUT / DIR_IN label, but not the label itself:

```python
>>> g=m.Gpio(0)
>>> 
>>> import mraa as m
>>> g.dir(DIR_OUT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'DIR_OUT' is not defined
>>> g.dir(DIR_IN)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'DIR_IN' is not defined
>>> ########################################
>>> g.dir(0)
0
>>> g.dir(1)
0
>>>help(m)
...
DATA
    DIR_IN = 1
    DIR_OUT = 0
    DIR_OUT_HIGH = 2
    DIR_OUT_LOW = 3

```

Using galileo v1 with  m.getVersion() ---> 'v0.6.1'
The same issue is encountered for DIR_OUT_LOW/ DIR_OUT_HIGH

Costin

**Comment by arfoll** [comment]
Use m.DIR_IN. that const comes from the mraa package so its not global.
