### ISSUE TITLE
Installation fails on Edison with Node.js v4.2.1

### ISSUE THREAD

**Issue by michael-p** [intel-iot-devkit/mraa#335]
Dear all,

I'm trying to install mraa on an Intel Edison (running Yocto) using `npm install mraa` but the installation fails (`"... Failed at the mraa@0.8.0 install script 'node-gyp rebuild'. ..."`). I'm not running the preinstalled node.js version (which is an old 0.10 I think) but instead installed node v4.2.1 from source. npm version is 2.14.8. Installing other packages works fine.

Is mraa not (yet) compatible with the most recent node version? If so, are there plans to update it?

Thanks,
Michael

**Comment by alext-mkrs** [comment]
Can you please post a full install process output? I wonder if this is the same as #333.

**Comment by michael-p** [comment]
Here is the full install output: https://gist.github.com/michael-p/b03bc7f06ad006ff0bdb

I also just rolled back to the old Node version (v0.10.38), installing and using mraa with that version works fine.

**Comment by xbolshe** [comment]
mraa 0.8.0 is compatible with node v4.x (Galileo Gen1):

![node421](https://cloud.githubusercontent.com/assets/10796236/10713276/f831e41c-7abe-11e5-9fdc-e9d8b6a7daed.jpg)

What SWIG, gcc, g++, cmake, make versions do you use?

**Comment by arfoll** [comment]
Need more info from your buildoutput, latest should work with node 4.x as @xbolshe points out

**Comment by michael-p** [comment]
Hi guys, thanks a lot for the fast help - really happy to hear that it does work on node 4 ! :)

Here are the version numbers:
```
root@Edison:~# node --version
v4.2.1
root@Edison:~# cat /sys/devices/virtual/dmi/id/board_name
BODEGA BAY
root@Edison:~# node -p "process.versions"
{ http_parser: '2.5.0',
  node: '4.2.1',
  v8: '4.5.103.35',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '46',
  openssl: '1.0.2d' }
root@Edison:~# uname -a
Linux Edison 3.10.17-poky-edison+ #1 SMP PREEMPT Fri Jun 19 12:06:40 CEST 2015 i686 GNU/Linux
root@Edison:~# make --version
GNU Make 4.0
Built for i586-poky-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@Edison:~# python --version
Python 2.7.3
root@Edison:~# g++ --version
g++ (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@Edison:~# gcc --version
gcc (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@Edison:~# swig -version

SWIG Version 3.0.5

Compiled with i586-poky-linux-g++  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -mstackrealign -fno-omit-frame-pointer --sysroot=/data/jenkins_worker/workspace/edison-weekly/out/linux64/build/tmp/sysroots/edison [i586-poky-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

In addition to the output of `npm install mraa` I already posted above here are the contents of npm-debug.log after the installation attempt: https://gist.github.com/michael-p/8a1f41e723ab75f564a8

If you need further information or have ideas what else I could test please let me know!

**Comment by xbolshe** [comment]
As I see: "0.8.0":"2015-09-22T16:08:06.701Z" and "modified":"2015-09-22T16:08:06.701Z"
But node 4.x patch was in October. Seems need to update a package in https://registry.npmjs.org/mraa

**Comment by xbolshe** [comment]
May you try to execute and post an output?

npm install node-gyp
node-gyp rebuild

**Comment by michael-p** [comment]
Ok so I first tried to compile mraa from source (the v0.8.0 tag) but make fails with the following output:
```
...
Scanning dependencies of target mraajs
[ 49%] Building CXX object src/javascript/CMakeFiles/mraajs.dir/mraajsJAVASCRIPT_wrap.cxx.o
In file included from /usr/local/include/node/node.h:42:0,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:156:
/usr/local/include/node/v8.h:336:1: error: expected unqualified-id before 'using'
 using Handle = Local<T>;
 ^
/usr/local/include/node/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
/usr/local/include/node/v8.h:353:33: error: 'nullptr' was not declared in this scope
   V8_INLINE MaybeLocal() : val_(nullptr) {}
                                 ^
/usr/local/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
/usr/local/include/node/v8.h:360:51: error: 'nullptr' was not declared in this scope
   V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
                                                   ^
/usr/local/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
/usr/local/include/node/v8.h:364:29: error: 'nullptr' was not declared in this scope
     out->val_ = IsEmpty() ? nullptr : this->val_;
                             ^
/usr/local/include/node/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
/usr/local/include/node/v8.h:430:50: error: 'nullptr' was not declared in this scope
   bool IsFirstPass() const { return callback_ != nullptr; }
                                                  ^
/usr/local/include/node/v8.h: At global scope:
/usr/local/include/node/v8.h:469:1: error: expected unqualified-id before 'using'
 using PhantomCallbackData = WeakCallbackInfo<T>;
 ^
/usr/local/include/node/v8.h:472:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum class WeakCallbackType { kParameter, kInternalFields };
 ^
/usr/local/include/node/v8.h:637:43: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
   PersistentBase(PersistentBase& other) = delete;  // NOLINT
                                           ^
/usr/local/include/node/v8.h:638:37: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
   void operator=(PersistentBase&) = delete;
                                     ^
/usr/local/include/node/v8.h:814:26: error: expected ',' or '...' before '&&' token
   V8_INLINE Global(Global&& other) : PersistentBase<T>(other.val_) {
                          ^
/usr/local/include/node/v8.h:814:34: error: invalid constructor; you probably meant 'v8::Global<T> (const v8::Global<T>&)'
   V8_INLINE Global(Global&& other) : PersistentBase<T>(other.val_) {
                                  ^
/usr/local/include/node/v8.h:822:40: error: expected ',' or '...' before '&&' token
   V8_INLINE Global& operator=(Global<S>&& rhs) {
                                        ^
/usr/local/include/node/v8.h:844:21: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
   Global(Global&) = delete;
                     ^
/usr/local/include/node/v8.h:845:29: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
   void operator=(Global&) = delete;
                             ^
/usr/local/include/node/v8.h: In constructor 'v8::Global<T>::Global()':
/usr/local/include/node/v8.h:790:42: error: 'nullptr' was not declared in this scope
   V8_INLINE Global() : PersistentBase<T>(nullptr) {}
                                          ^
/usr/local/include/node/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>)':
/usr/local/include/node/v8.h:824:18: error: 'rhs' was not declared in this scope
     if (this != &rhs) {
                  ^
/usr/local/include/node/v8.h:827:18: error: 'nullptr' was not declared in this scope
       rhs.val_ = nullptr;
                  ^
/usr/local/include/node/v8.h: In member function 'v8::Global<T> v8::Global<T>::Pass()':
/usr/local/include/node/v8.h:834:44: error: expected '>' before '&&' token
   Global Pass() { return static_cast<Global&&>(*this); }
                                            ^
/usr/local/include/node/v8.h:834:44: error: expected '(' before '&&' token
/usr/local/include/node/v8.h:834:46: error: expected identifier before '>' token
   Global Pass() { return static_cast<Global&&>(*this); }
                                              ^
/usr/local/include/node/v8.h:834:54: error: expected ')' before ';' token
   Global Pass() { return static_cast<Global&&>(*this); }
                                                      ^
/usr/local/include/node/v8.h: At global scope:
/usr/local/include/node/v8.h:852:1: error: expected unqualified-id before 'using'
 using UniquePersistent = Global<T>;
 ^
In file included from /usr/local/include/node/v8.h:23:0,
                 from /usr/local/include/node/node.h:42,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:156:
/usr/local/include/node/v8.h:1092:52: error: 'nullptr' was not declared in this scope
                             ScriptOrigin* origin = nullptr));
                                                    ^
/usr/local/include/node/v8config.h:347:48: note: in definition of macro 'V8_DEPRECATE_SOON'
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from /usr/local/include/node/node.h:42:0,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:156:
/usr/local/include/node/v8.h:1095:30: error: 'nullptr' was not declared in this scope
       ScriptOrigin* origin = nullptr);
                              ^
/usr/local/include/node/v8.h:2075:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum class NewStringType { kNormal, kInternalized };
 ^
/usr/local/include/node/v8.h:2283:42: error: 'v8::NewStringType' is not a class or namespace
     kNormalString = static_cast<int>(v8::NewStringType::kNormal),
                                          ^
/usr/local/include/node/v8.h:2284:48: error: 'v8::NewStringType' is not a class or namespace
     kInternalizedString = static_cast<int>(v8::NewStringType::kInternalized)
                                                ^
/usr/local/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/usr/local/include/node/v8.h:3205:36: error: 'nullptr' was not declared in this scope
     return NewInstance(context, 0, nullptr);
                                    ^
/usr/local/include/node/v8.h: At global scope:
/usr/local/include/node/v8.h:3350:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum class ArrayBufferCreationMode { kInternalized, kExternalized };
 ^
/usr/local/include/node/v8.h:3434:38: error: 'ArrayBufferCreationMode' is not a class or namespace
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                      ^
/usr/local/include/node/v8.h:3797:38: error: 'ArrayBufferCreationMode' is not a class or namespace
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                      ^
/usr/local/include/node/v8.h:4435:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum class PropertyHandlerFlags {
 ^
/usr/local/include/node/v8.h:4457:36: error: 'PropertyHandlerFlags' is not a class or namespace
       PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                    ^
/usr/local/include/node/v8.h:4485:36: error: 'PropertyHandlerFlags' is not a class or namespace
       PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                    ^
/usr/local/include/node/v8.h: In member function 'void v8::ObjectTemplate::SetIndexedPropertyHandler(v8::IndexedPropertyGetterCallback, v8::IndexedPropertySetterCallback, v8::IndexedPropertyQueryCallback, v8::IndexedPropertyDeleterCallback, v8::IndexedPropertyEnumeratorCallback, v8::Local<v8::Value>)':
/usr/local/include/node/v8.h:4617:77: error: call to 'v8::IndexedPropertyHandlerConfiguration::IndexedPropertyHandlerConfiguration(v8::IndexedPropertyGetterCallback, v8::IndexedPropertySetterCallback, v8::IndexedPropertyQueryCallback, v8::IndexedPropertyDeleterCallback, v8::IndexedPropertyEnumeratorCallback, v8::Local<v8::Value>, v8::PropertyHandlerFlags)' uses the default argument for parameter 7, which is not yet defined
                                                    deleter, enumerator, data));
                                                                             ^
In file included from /usr/local/include/node/v8.h:23:0,
                 from /usr/local/include/node/node.h:42,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:156:
/usr/local/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/usr/local/include/node/v8.h:7164:27: error: 'nullptr' was not declared in this scope
   if (V8_UNLIKELY(val_ == nullptr)) V8::ToLocalEmpty();
                           ^
/usr/local/include/node/v8config.h:353:54: note: in definition of macro 'V8_UNLIKELY'
 # define V8_UNLIKELY(condition) (__builtin_expect(!!(condition), 0))
                                                      ^
In file included from /usr/local/include/node/node.h:42:0,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:156:
/usr/local/include/node/v8.h: In member function 'void v8::Template::Set(v8::Isolate*, const char*, v8::Local<v8::Data>)':
/usr/local/include/node/v8.h:7609:46: error: 'NewStringType' is not a class or namespace
   Set(v8::String::NewFromUtf8(isolate, name, NewStringType::kNormal)
                                              ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx: At global scope:
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:894:7: error: 'Handle' in namespace 'v8' does not name a template type
   v8::Handle<v8::Value> err;
       ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx: In member function 'virtual void OverloadErrorHandler::error(int, const char*)':
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:889:5: error: 'err' was not declared in this scope
     err = v8::Exception::Error(SWIGV8_STRING_NEW(msg));
     ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx: At global scope:
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:39: error: 'Handle' is not a member of 'v8'
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                       ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:60: error: expected primary-expression before '>' token
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                            ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:62: error: 'objRef' was not declared in this scope
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                              ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:70: error: expected primary-expression before 'void'
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                      ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:97: error: expected primary-expression before '*' token
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                                                 ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:98: error: 'info' was not declared in this scope
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                                                  ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:104: error: expected primary-expression before 'int'
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                                                        ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:113: error: expression list treated as compound expression in initializer [-fpermissive]
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                                                                 ^
/home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:957:115: error: expected ',' or ';' before '{' token
 static int SWIG_V8_ConvertInstancePtr(v8::Handle<v8::Object> objRef, void **ptr, swig_type_info *info, int flags) {
                                                                                                                   ^
In file included from /usr/include/c++/4.9.1/stdexcept:38:0,
                 from /home/root/mraa-0.8.0/build/src/javascript/mraajsJAVASCRIPT_wrap.cxx:1515:
/usr/include/c++/4.9.1/exception:35:37: error: expected declaration before end of line
 #pragma GCC visibility push(default)
                                     ^
src/javascript/CMakeFiles/mraajs.dir/build.make:60: recipe for target 'src/javascript/CMakeFiles/mraajs.dir/mraajsJAVASCRIPT_wrap.cxx.o' failed
make[2]: *** [src/javascript/CMakeFiles/mraajs.dir/mraajsJAVASCRIPT_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:231: recipe for target 'src/javascript/CMakeFiles/mraajs.dir/all' failed
make[1]: *** [src/javascript/CMakeFiles/mraajs.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2
root@Edison:~/mraa-0.8.0/build# 
```

Then, in build/src/javascript:
```
root@Edison:~/mraa-0.8.0/build/src/javascript# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.2.1 | linux | ia32
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/root/mraa-0.8.0/build/src/javascript/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/root/.node-gyp/4.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/root/.node-gyp/4.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/root/mraa-0.8.0/build/src/javascript',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/root/mraa-0.8.0/build/src/javascript/build'
make: *** No rule to make target 'Release/obj.target/mraa/src/x86/intel_minnow_byt_compatible.o', needed by 'Release/obj.target/mraa.node'.  Stop.
make: Leaving directory '/home/root/mraa-0.8.0/build/src/javascript/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.17-poky-edison+
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/root/mraa-0.8.0/build/src/javascript
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

I also see that 3059c06fa05c4a5536ec82d00bd991891956704d from October 3rd mentions node 4 support but release 0.8.0 is from September 22nd. Maybe node 4 support is just not yet on npm?
However, I also tried the above procedure on the master branch and node-gyp rebuild fails there as well (with the same error message).

**Comment by arfoll** [comment]
Yes correct, you need master, npm has the latest release version which doesn't support it yet.

**Comment by kyrylkov** [comment]
@arfoll When are you planning to do a release supporting Node.js 4.x.x & 5.x.x ?

**Comment by tingleby** [comment]
Ill give what we have on master a go and then tag 0.8.1

**Comment by kyrylkov** [comment]
Great!
