### ISSUE TITLE
Error initialising  pins on Intel Joule

### ISSUE THREAD

**Issue by ihabZhaika** [intel-iot-devkit/mraa#596]
hi,
i am using mraa Version v1.4.0 on Intel GT Tuchuck with python 2.7 running on ubuntu 16.04
according to the page over here 

https://github.com/intel-iot-devkit/mraa/blob/master/docs/grossetete.md

pin NO. 20 is GPIO , and No.26 is pmw
20	I2S1MCL	GPIO
26	PWM0	GPIO PWM

so when i try to use the pins i get
**Error initialising PWM on pin**

### The code
import mraa
import time

print (mraa.getVersion())
print (mraa.getPlatformName())
print (mraa.getPinName(20))
print (mraa.getPinName(26))
motor1_pmw_pin_26 = mraa.Pwm(26)
motor1_gpio_pin_20 = mraa.Gpio(20)

i get this result

usr/bin/python2.7 /home/ubuntu/PycharmProjects/joule/main.py
v1.4.0
Traceback (most recent call last):
Intel GT Tuchuck
I2S1MCL
PWM0
  File "/home/ubuntu/PycharmProjects/joule/main.py", line 8, in <module>
    motor1_pmw_pin_26 = mraa.Pwm(26)
  File "/usr/lib/python2.7/dist-packages/mraa.py", line 1336, in __init__
    this = _mraa.new_Pwm(pin, owner, chipid)
ValueError: Error initialising PWM on pin

Process finished with exit code 1

**Comment by ihabZhaika** [comment]
seems Root user problem
