### ISSUE TITLE
Installation failed on raspberry pi 2

### ISSUE THREAD

**Issue by ppopadiyn** [intel-iot-devkit/mraa#629]
Hi,

I tried installing mraa on raspberry pi 2 via `npm install mraa`. And the installation failed at the following line: 
`mraa.target.mk:139: recipe for target 'Release/obj.target/mraa/src/mraajsJAVASCRIPT_wrap.o' failed`.

At the end is the full output of the 'npm install' command. I checked the various build requirements. Not sure what I need and what I don't, but this is what I have on the board:

- node v6.9.1
- npm v4.0.5
- swig 3.0.11
- Python 2.7.3
- GNU Make 4.0
- cmake version 2.8.9
- gcc version 4.8.2

Any ideas ? Thanks in advance.

Here is the complete npm output

```
> mraa@1.5.1 install /home/pi/work/test-mraa/node_modules/mraa
> node-gyp rebuild

make: Entering directory '/home/pi/work/test-mraa/node_modules/mraa/build'
  CC(target) Release/obj.target/mraa/src/x86/intel_gt_tuchuck.o
  CC(target) Release/obj.target/mraa/src/x86/up.o
  CC(target) Release/obj.target/mraa/src/x86/intel_cherryhills.o
  CC(target) Release/obj.target/mraa/src/x86/intel_sofia_3gr.o
  CC(target) Release/obj.target/mraa/src/x86/intel_minnow_byt_compatible.o
  CC(target) Release/obj.target/mraa/src/x86/intel_nuc5.o
  CC(target) Release/obj.target/mraa/src/x86/intel_de3815.o
  CC(target) Release/obj.target/mraa/src/x86/intel_edison_fab_c.o
../src/x86/intel_edison_fab_c.c: In function ‘mraa_intel_edison_aio_init_pre’:
../src/x86/intel_edison_fab_c.c:335:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (aio > plat->aio_count) {
             ^
../src/x86/intel_edison_fab_c.c: In function ‘is_arduino_board’:
../src/x86/intel_edison_fab_c.c:1213:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i=0; i<(sizeof(gpiochip_idx)/sizeof(gpiochip_idx[0])); i++) {
                ^
  CC(target) Release/obj.target/mraa/src/x86/intel_galileo_rev_g.o
  CC(target) Release/obj.target/mraa/src/x86/intel_galileo_rev_d.o
  CC(target) Release/obj.target/mraa/src/x86/x86.o
  CC(target) Release/obj.target/mraa/src/arm/banana.o
../src/arm/banana.c: In function ‘mraa_banana_mmap_write’:
../src/arm/banana.c:110:24: warning: unused variable ‘addr’ [-Wunused-variable]
     volatile uint32_t* addr;
                        ^
../src/arm/banana.c: In function ‘mraa_banana’:
../src/arm/banana.c:562:52: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         b->uart_dev[b->uart_dev_count].device_path = serialdev[uart3];
                                                    ^
../src/arm/banana.c:569:52: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         b->uart_dev[b->uart_dev_count].device_path = serialdev[uart4];
                                                    ^
../src/arm/banana.c:575:52: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         b->uart_dev[b->uart_dev_count].device_path = serialdev[uart7];
                                                    ^
../src/arm/banana.c:586:52: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         b->uart_dev[b->uart_dev_count].device_path = serialdev[uart2];
                                                    ^
  CC(target) Release/obj.target/mraa/src/arm/beaglebone.o
../src/arm/beaglebone.c: In function ‘mraa_beaglebone_pwm_init_replace’:
../src/arm/beaglebone.c:329:13: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
             syslog(LOG_ERR, "pwm: Failed to open %s for writing, check access rights for user");
             ^
../src/arm/beaglebone.c: In function ‘mraa_beaglebone’:
../src/arm/beaglebone.c:379:18: warning: variable ‘uart3_enabled’ set but not used [-Wunused-but-set-variable]
     unsigned int uart3_enabled = 0;
                  ^
  CC(target) Release/obj.target/mraa/src/arm/raspberry_pi.o
../src/arm/raspberry_pi.c: In function ‘mraa_raspberry_pi_mmap_write’:
../src/arm/raspberry_pi.c:117:24: warning: unused variable ‘addr’ [-Wunused-variable]
     volatile uint32_t* addr;
                        ^
../src/arm/raspberry_pi.c: In function ‘mraa_raspberry_pi’:
../src/arm/raspberry_pi.c:237:39: warning: assignment makes integer from pointer without a cast [enabled by default]
                     platform_detected = PLATFORM_RASPBERRY_PI_ZERO;
                                       ^
../src/arm/raspberry_pi.c:500:28: warning: comparison between pointer and integer [enabled by default]
         (platform_detected == PLATFORM_RASPBERRY_PI_ZERO)) {
                            ^
../src/arm/raspberry_pi.c:500:28: warning: comparison with string literal results in unspecified behavior [-Waddress]
  CC(target) Release/obj.target/mraa/src/arm/96boards.o
../src/arm/96boards.c: In function ‘mraa_96boards’:
../src/arm/96boards.c:93:40: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
             b->uart_dev[0].device_path = db410c_serialdev[0];
                                        ^
../src/arm/96boards.c:94:40: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
             b->uart_dev[1].device_path = db410c_serialdev[1];
                                        ^
../src/arm/96boards.c:98:40: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
             b->uart_dev[0].device_path = hikey_serialdev[0];
                                        ^
../src/arm/96boards.c:99:40: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
             b->uart_dev[1].device_path = hikey_serialdev[1];
                                        ^
../src/arm/96boards.c:77:9: warning: unused variable ‘ch’ [-Wunused-variable]
    char ch;
         ^
../src/arm/96boards.c:75:11: warning: unused variable ‘pin’ [-Wunused-variable]
    int i, pin;
           ^
  CC(target) Release/obj.target/mraa/src/arm/arm.o
  CC(target) Release/obj.target/mraa/src/uart_ow/uart_ow.o
  CC(target) Release/obj.target/mraa/src/firmata/firmata_mraa.o
../src/firmata/firmata_mraa.c: In function ‘mraa_firmata_i2c_init_bus_replace’:
../src/firmata/firmata_mraa.c:99:42: warning: value computed is not used [-Wunused-value]
     buff[2] = delay & 0xFF, (delay >> 8) & 0xFF;
                                          ^
../src/firmata/firmata_mraa.c: In function ‘mraa_firmata_i2c_read_word_data’:
../src/firmata/firmata_mraa.c:220:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             uint16_t data = (uint16_t) rawdata;
                             ^
  CC(target) Release/obj.target/mraa/src/firmata/firmata.o
  CC(target) Release/obj.target/mraa/src/iio/iio.o
  CC(target) Release/obj.target/mraa/src/uart/uart.o
../src/uart/uart.c: In function ‘mraa_uart_init_raw’:
../src/uart/uart.c:263:12: warning: ‘dev’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (dev != NULL) {
            ^
  CC(target) Release/obj.target/mraa/src/aio/aio.o
../src/aio/aio.c: In function ‘mraa_aio_init’:
../src/aio/aio.c:112:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (aio >= board->aio_count) {
             ^
  CC(target) Release/obj.target/mraa/src/spi/spi.o
  CC(target) Release/obj.target/mraa/src/pwm/pwm.o
  CC(target) Release/obj.target/mraa/src/i2c/i2c.o
  CC(target) Release/obj.target/mraa/src/gpio/gpio.o
  CC(target) Release/obj.target/mraa/src/mraa.o
../src/mraa.c: In function ‘mraa_deinit’:
../src/mraa.c:228:9: warning: unused variable ‘i’ [-Wunused-variable]
     int i = 0;
         ^
  CC(target) Release/obj.target/mraa/src/version.o
  CXX(target) Release/obj.target/mraa/src/mraajsJAVASCRIPT_wrap.o
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘int SwigV8Packed_Check(v8::Handle<v8::Value>)’:
../src/mraajsJAVASCRIPT_wrap.cxx:1240:97: warning: ‘v8::Local<v8::Value> v8::Object::GetHiddenValue(v8::Local<v8::String>)’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:2955): Use v8::Object::GetPrivate instead. [-Wdeprecated-declarations]
   v8::Handle<v8::Value> flag = objRef->GetHiddenValue(SWIGV8_STRING_NEW("__swig__packed_data__"));
                                                                                                 ^
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘v8::Handle<v8::Value> SWIGV8_NewPackedObj(void*, size_t, swig_type_info*)’:
../src/mraajsJAVASCRIPT_wrap.cxx:1320:91: warning: ‘bool v8::Object::SetHiddenValue(v8::Local<v8::String>, v8::Local<v8::Value>)’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:2953): Use v8::Object::SetPrivate instead. [-Wdeprecated-declarations]
   obj->SetHiddenValue(SWIGV8_STRING_NEW("__swig__packed_data__"), SWIGV8_BOOLEAN_NEW(true));
                                                                                           ^
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘void SWIGV8_AddStaticVariable(v8::Handle<v8::Object>, const char*, SwigV8AccessorGetterCallback, SwigV8AccessorSetterCallback)’:
../src/mraajsJAVASCRIPT_wrap.cxx:1457:61: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:2743): Use maybe version [-Wdeprecated-declarations]
   obj->SetAccessor(SWIGV8_SYMBOL_NEW(symbol), getter, setter);
                                                             ^
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_I2c_read(const SwigV8Arguments&)’:
../src/mraajsJAVASCRIPT_wrap.cxx:7066:54: error: no matching function for call to ‘New(char*, int&)’
     jsresult = node::Buffer::New((char*) arg2, result);
                                                      ^
../src/mraajsJAVASCRIPT_wrap.cxx:7066:54: note: candidates are:
In file included from ../src/mraajsJAVASCRIPT_wrap.cxx:1676:0:
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 2 provided
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 2 provided
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_I2c_readBytesReg(const SwigV8Arguments&)’:
../src/mraajsJAVASCRIPT_wrap.cxx:7234:54: error: no matching function for call to ‘New(char*, int&)’
     jsresult = node::Buffer::New((char*) arg3, result);
                                                      ^
../src/mraajsJAVASCRIPT_wrap.cxx:7234:54: note: candidates are:
In file included from ../src/mraajsJAVASCRIPT_wrap.cxx:1676:0:
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 2 provided
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 2 provided
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_Spi_write(const SwigV8Arguments&)’:
../src/mraajsJAVASCRIPT_wrap.cxx:8593:54: error: no matching function for call to ‘New(char*, int&)’
     jsresult = node::Buffer::New((char*) result, arg3);
                                                      ^
../src/mraajsJAVASCRIPT_wrap.cxx:8593:54: note: candidates are:
In file included from ../src/mraajsJAVASCRIPT_wrap.cxx:1676:0:
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 2 provided
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 2 provided
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_Uart_read(const SwigV8Arguments&)’:
../src/mraajsJAVASCRIPT_wrap.cxx:9167:54: error: no matching function for call to ‘New(char*, int&)’
     jsresult = node::Buffer::New((char*) arg2, result);
                                                      ^
../src/mraajsJAVASCRIPT_wrap.cxx:9167:54: note: candidates are:
In file included from ../src/mraajsJAVASCRIPT_wrap.cxx:1676:0:
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 2 provided
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 2 provided
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘void SWIG_V8_SetModule(void*, swig_module_info*)’:
../src/mraajsJAVASCRIPT_wrap.cxx:9899:77: warning: ‘bool v8::Object::SetHiddenValue(v8::Local<v8::String>, v8::Local<v8::Value>)’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:2953): Use v8::Object::SetPrivate instead. [-Wdeprecated-declarations]
   global_obj->SetHiddenValue(SWIGV8_STRING_NEW("swig_module_info_data"), mod);
                                                                             ^
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘swig_module_info* SWIG_V8_GetModule(void*)’:
../src/mraajsJAVASCRIPT_wrap.cxx:9905:106: warning: ‘v8::Local<v8::Value> v8::Object::GetHiddenValue(v8::Local<v8::String>)’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:2955): Use v8::Object::GetPrivate instead. [-Wdeprecated-declarations]
   v8::Local<v8::Value> moduleinfo = global_obj->GetHiddenValue(SWIGV8_STRING_NEW("swig_module_info_data"));
                                                                                                          ^
mraa.target.mk:139: recipe for target 'Release/obj.target/mraa/src/mraajsJAVASCRIPT_wrap.o' failed
make: *** [Release/obj.target/mraa/src/mraajsJAVASCRIPT_wrap.o] Error 1
make: Leaving directory '/home/pi/work/test-mraa/node_modules/mraa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/work/test-mraa/node_modules/mraa
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN test-mraa@1.0.0 No description
npm WARN test-mraa@1.0.0 No repository field.
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mraa"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! mraa@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mraa@1.5.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

```

**Comment by AnandVetcha** [comment]
Following article mentions the steps to be followed to install MRAA on Rasberry Pi:
https://www.ics.com/blog/getting-started-mraa-raspberry-pi
Did you try steps mentioned in above link?

**Comment by alext-mkrs** [comment]
Looks like there's something wrong with the swig-generated code (just one example, there are more errors):
```
../src/mraajsJAVASCRIPT_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_I2c_read(const SwigV8Arguments&)’:
../src/mraajsJAVASCRIPT_wrap.cxx:7066:54: error: no matching function for call to ‘New(char*, int&)’
     jsresult = node::Buffer::New((char*) arg2, result);
```

In general, SWIG has problems with recent versions of v8, as they have [no active JS section maintainer](https://github.com/swig/swig/issues/804). Node 7, for example is broken. Try downgrading Node to something out of 5.x family, that used to work and is actually built for each mraa commit.

**Comment by alext-mkrs** [comment]
@ppopadiyn, have you tried suggestions from this thread, is this still actual at all?

**Comment by ppopadiyn** [comment]
Hi there,

After some pause (almost 2 months)... sorry for the delay, I tried installing mraa this morning again. I am using the latest distribution of raspbian jessy with pixel on raspberry 3. This time I tried using nodejs v4.8.0 as you suggested. Unfortunately, I am still not able to install mraa using the ```npm install mraa``` command. I am getting exactly the same error :(. That's why I tried to follow the instructions from here https://www.ics.com/blog/getting-started-mraa-raspberry-pi
I think I have some progress, but now I am getting the following error:

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libmraa.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Documents/Iot/mraa/examples/javascript/test.js:2:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by arfoll** [comment]
So this error indicates you don't have libmraa.so.1 in your LD_LIBRARY_PATH? so did you maybe forget to add -DCMAKE_INSTALL_PREFIX=/usr and ended up with installing stuff in /usr/local?

**Comment by alext-mkrs** [comment]
Most probably, that article instructs to run 'cmake .. ' and then just 'make install', without any additional parameters.

**Comment by ppopadiyn** [comment]
Yes, I have't used -DCMAKE_INSTALL_PREFIX=/usr. After I did a second try with ```cmake -DCMAKE_INSTALL_PREFIX=/usr .. ```, everything seems to work fine for now and I managed to _require('mraa')_  in a javascript file.
At some point I would definitely try again to install it via ```npm install```, but I guess this should be enough for now to start playing with it.
