### ISSUE TITLE
Building mraa.node for Linkit Smart 7688 with error: ELF file ABI version invalid

### ISSUE THREAD

**Issue by Avena83** [intel-iot-devkit/mraa#904]
### Libmraa installed without problem, but with NodeJS (mraa.node) problem

**node -r mraa**
```
module.js:604
 return process.dlopen(module, path._makeLong(filename));
         ^

Error: /usr/lib/node_modules/mraa/mraa.node: ELF file ABI version invalid
  at Error (native)
  at Object.Module._extensions..node (module.js:604:18)
  at Module.load (module.js:494:32)
  at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at module.js:677:12
  at Array.forEach (native)
  at Function.Module._preloadModules (module.js:676:12)
  at preloadModules (bootstrap_node.js:367:38)
```
**readelf -a /usr/lib/node_modules/mraa/mraa.node | head -n 10**

```
ELF Header:
 Magic:  7f 45 4c 46 01 01 01 00 05 00 00 00 00 00 00 00 
 Class:               ELF32
 Data:               2's complement, little endian
 Version:              1 (current)
 OS/ABI:              UNIX - System V
 ABI Version:            5
 Type:               DYN (Shared object file)
 Machine:              MIPS R3000
 Version:              0x1
```
**readelf -a /usr/bin/node | head -n 10**

```
ELF Header:

 Magic:  7f 45 4c 46 01 01 01 00 01 00 00 00 00 00 00 00 
 Class:               ELF32
 Data:               2's complement, little endian
 Version:              1 (current)
 OS/ABI:              UNIX - System V
 ABI Version:            1
 Type:               EXEC (Executable file)
 Machine:              MIPS R3000
 Version:              0x1
```

**Just few information**
```
-- INFO - libmraa Version v1.9.0
-- INFO - cmake Version 3.4.3
-- INFO - Override arch is mips
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is exact version "2.7.15")
-- Could NOT find PythonInterp: Found unsuitable version "2.7.15", but required is at least "3" (found /usr/bin/python)
-- Could NOT find PythonInterp: Found unsuitable version "2.7.15", but required is at least "3.2" (found /usr/bin/python)
-- INFO - Adding firmata backend support
-- INFO - Adding support for platform ALL
-- INFO - Adding support for all platforms
INFO - Adding MIPS platforms
-- Found SWIG: /usr/bin/swig (found version "3.0.12") 
-- INFO - NODE_ROOT_DIR is /usr/include/node
-- Found Nodejs: /usr/bin/node (found version "6.14.3") 
-- Found v8: /usr/include/node/v8.h (found version "5.1.281.111")
-- INFO - swig Version 3.0.12
-- INFO - CXX compiler Version GNU 5.4.0
-- INFO - Using V8 version > 3 so requiring C++11 compiler
-- INFO - install NODE modules to /usr/lib/node_modules/mraa/
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mraa/build
```
Need help to solve this problem with mraa.node
Many thanks for any useful support!

**Comment by Propanu** [comment]
Hi @Avena83, how did you solve this?
